#!/usr/bin/env bash

function printHelp() {
  cat <<EOF
USAGE:
    run-all-tests [--app <APP_PATH>]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --app <APP_PATH>            Path the app to test
EOF
}
APP_PATH=""
while [[ ${#} > 0 ]]; do

    case "${1}" in

        -h|--help)
          printHelp
          exit 1
        ;;

        --app)
          APP_PATH="${2}";
          shift
        ;;

    esac
    shift
done

DATA_DIR="$(pwd)/data"

if [ ! -z "${APP_PATH}" ]; then

    for SAMPLE in $(ls -1 ${DATA_DIR}/needles-*.txt); do
      cd ${APP_PATH}
      build
      gtimeout 60s run-test \
        --haystack ${DATA_DIR}/haystack.txt \
        --needles ${SAMPLE} \
        --warmup-haystack ${DATA_DIR}/warmup-haystack.txt \
        --warmup-needles ${DATA_DIR}/warmup-needles.txt \
        --warmup-result e
      cd - 1>/dev/null
    done

else

  for APP in $(ls -1 round-1); do
    for SAMPLE in $(ls -1 ${DATA_DIR}/needles-*.txt); do
      cd round-1/${APP}/

      if [ -f run-test ]; then
        build
        gtimeout 60s run-test \
          --haystack ${DATA_DIR}/haystack.txt \
          --needles ${SAMPLE} \
          --warmup-haystack ${DATA_DIR}/warmup-haystack.txt \
          --warmup-needles ${DATA_DIR}/warmup-needles.txt \
          --warmup-result e
      fi

      cd - 1>/dev/null

    done
  done
fi



