#! /usr/bin/python
import sys
import argparse

parser = argparse.ArgumentParser(description='Needles in a haystack, needle power.')
parser.add_argument("-n", "--needles", required=True,
    help="name of the needles file")
args = vars(parser.parse_args())

d = {}

with open(args['needles']) as needles:
    for line in needles:
        d[line] = False

try:
    for line in iter(sys.stdin.readline, b''):
        if line in d:
            sys.stdout.write(line)
except KeyboardInterrupt:
    sys.stdout.flush()
    pass