#!/usr/bin/env php
<?php
ini_set('memory_limit', '256M');
$lines = file($argv[2], FILE_SKIP_EMPTY_LINES);
$lines = array_flip($lines);
while($line = fgets(STDIN)){
  if (isset($lines[$line])) {
    echo $line;
  }
}
?>