#!/usr/bin/env php
<?php
ini_set('memory_limit', '-1');
$lines = file($argv[2], FILE_SKIP_EMPTY_LINES);
$lines = array_flip($lines);
$handle = fopen($argv[4], "r");
if ($handle) {
    while (($line = fgets($handle)) !== false) {
      if (isset($lines[$line])) {
        echo $line;
      }
    }
    fclose($handle);
}
?>