#!/usr/bin/env node

const fs = require('fs');
const readline = require('readline');

const needles = new Set();

const arg = process.argv[process.argv.indexOf('--needles') + 1];

readline.createInterface({ input: fs.createReadStream(arg) })
  .on('line', line => needles.add(line))
  .on('close', line => findNeedles(line))

function findNeedles() {
  readline
    .createInterface({ input: process.stdin })
    .on('line', line => {
      if (needles.has(line)) {
        needles.delete(line)
        console.log(line)
      }
    })
}
